---
- name: "Manage avahi packages"
  become: true
  ansible.builtin.package:
    name: "{{ avahi_package_name }}"
    state: "{{ avahi_package_state }}"
  notify: "Restart avahi service"

- name: "Gather package facts"
  ansible.builtin.package_facts:

- name: "Manage avahi services"
  become: true
  ansible.builtin.service:
    name: "{{ avahi_service_name }}"
    state: "{{ avahi_service_state }}"
    enabled: "{{ avahi_service_enabled }}"
  when: "'avahi' in ansible_facts.packages"

- name: "Manage avahi firewall policy"
  become: true
  ansible.posix.firewalld:
    service: "{{ avahi_firewall_service }}"
    state: "{{ avahi_firewall_state }}"
    zone: "{{ avahi_firewall_zone | default(omit) }}"
    immediate: "{{ avahi_firewall_immediate }}"
    permanent: "{{ avahi_firewall_permanent }}"
  when: "'firewalld' in ansible_facts.packages"
